#Spring Boot 기본 설정
spring.application.name=chatbot  # 프로젝트(애플리케이션) 이름

# CORS 및 쿠키 관련 환경변수
app.allowed.origins=http://192.168.0.15:8089,http://192.168.0.15:9011,http://59.3.103.182:8089,http://59.3.103.182:9011

# FastAPI backend URL used by `FastApiService`
fastapi.base-url=http://localhost:8478

# 로컬, 개발서버 maria db 셋팅
  spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
  spring.datasource.url=jdbc:mariadb://192.168.0.15:3307/chatbot_db?characterEncoding=UTF-8&serverTimezone=UTC&allowMultiQueries=true
  spring.datasource.username=root
  spring.datasource.password=asdf

#JPA (Hibernate) 관련 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 서버 포트
server.address=0.0.0.0
server.port=9011

# HTTPS(SSL) 통신 활성화 설정
# server.ssl.enabled=true
# server.ssl.key-store=classpath:keystore.p12
# server.ssl.key-store-password=123456
# server.ssl.key-store-type=PKCS12