#Spring Boot 기본 설정
spring.application.name=chatbot  # 프로젝트(애플리케이션) 이름

# 로컬, 개발서버 maria db 셋팅
  spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
  spring.datasource.url=jdbc:mariadb://192.168.0.15:3307/chatbot_db?characterEncoding=UTF-8&serverTimezone=UTC&allowMultiQueries=true
  spring.datasource.username=root
  spring.datasource.password=asdf

#JPA (Hibernate) 관련 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 서버 포트
server.port=8080

# FastAPI 서버 연동 설정
fastapi.base-url=http://192.168.0.15:8478
